#!/usr/bin/env python3
"""
evaluate_prompts.py — CLI runner for the offline system prompt scoring framework.

Usage:
    python scripts/evaluate_prompts.py
    python scripts/evaluate_prompts.py --dataset eval/golden_dataset.jsonl
    python scripts/evaluate_prompts.py --max-cases 5
    python scripts/evaluate_prompts.py --tags correlated_subquery critical
    python scripts/evaluate_prompts.py --output eval/results/run_001.json

Requires:
    - Bedrock configured (AWS credentials + .env with BEDROCK_MODEL_ID)
    - Golden dataset at eval/golden_dataset.jsonl (generated by this repo)

Exit codes:
    0  — All cases passed (composite score ≥ threshold)
    1  — One or more cases failed
    2  — Fatal error (Bedrock not configured, dataset not found, etc.)
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

# ── Ensure project root is on sys.path ───────────────────────────────────────
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROJECT_ROOT))

from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn, TaskProgressColumn
from rich.rule import Rule
from rich.table import Table
from rich import box

from dotenv import load_dotenv

load_dotenv()

console = Console()
logging.basicConfig(level=logging.WARNING)  # suppress debug noise; Rich handles display


# ── Score → color mapping ─────────────────────────────────────────────────────

def _score_color(score: float) -> str:
    if score >= 0.80:
        return "bold green"
    elif score >= 0.60:
        return "bold yellow"
    else:
        return "bold red"


def _fmt(score: float) -> str:
    return f"[{_score_color(score)}]{score:.0%}[/]"


def _pass_fail(score: float, threshold: float) -> str:
    return "[bold green]PASS[/]" if score >= threshold else "[bold red]FAIL[/]"


# ── Main evaluation runner ────────────────────────────────────────────────────

def run_evaluation(args: argparse.Namespace) -> int:
    """Run the evaluation and return an exit code."""
    from src.config.settings import get_settings

    settings = get_settings()
    if not settings.bedrock_configured:
        console.print(
            Panel(
                "[bold red]❌ Bedrock is not configured.[/]\n\n"
                "Please set the following in your [bold].env[/] file:\n"
                "  • [cyan]AWS_ACCESS_KEY_ID[/]\n"
                "  • [cyan]AWS_SECRET_ACCESS_KEY[/]\n"
                "  • [cyan]AWS_REGION[/]\n"
                "  • [cyan]BEDROCK_MODEL_ID[/]",
                title="Configuration Error",
                border_style="red",
            )
        )
        return 2

    from src.eval.prompt_evaluator import PromptEvaluator, PASS_THRESHOLD
    from src.prompts.optimization_prompt import OPTIMIZATION_PROMPT_VERSION

    dataset_path = Path(args.dataset)
    if not dataset_path.exists():
        console.print(f"[bold red]❌ Dataset not found:[/] {dataset_path}")
        return 2

    # ── Header ────────────────────────────────────────────────────────────
    console.print()
    console.print(
        Panel.fit(
            f"[bold cyan]🧪 Prompt Evaluation Suite[/]\n"
            f"[dim]Prompt Version:[/] [bold]{OPTIMIZATION_PROMPT_VERSION}[/]   "
            f"[dim]Dataset:[/] [bold]{dataset_path}[/]   "
            f"[dim]Pass Threshold:[/] [bold]{PASS_THRESHOLD:.0%}[/]",
            border_style="cyan",
        )
    )
    console.print()

    evaluator = PromptEvaluator(pass_threshold=PASS_THRESHOLD)

    # ── Run with progress bar ─────────────────────────────────────────────
    # Load cases first so we know the total
    cases = evaluator._load_dataset(
        dataset_path,
        tags_filter=args.tags if args.tags else None,
    )
    if args.max_cases:
        cases = cases[: args.max_cases]

    if not cases:
        console.print("[yellow]⚠️  No test cases matched the given filters.[/]")
        return 2

    console.print(f"  Running [bold]{len(cases)}[/] test case(s)...\n")

    results = []
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TaskProgressColumn(),
        console=console,
    ) as progress:
        task = progress.add_task("[cyan]Evaluating...", total=len(cases))
        for tc in cases:
            progress.update(task, description=f"[cyan]{tc.id}[/] — {tc.description[:50]}")
            result = evaluator._evaluate_single(tc)
            results.append(result)
            progress.advance(task)

    from src.eval.prompt_evaluator import PromptEvaluator
    report = evaluator._aggregate(results, OPTIMIZATION_PROMPT_VERSION)

    # ── Per-case results table ────────────────────────────────────────────
    console.print()
    console.print(Rule("[bold]Per-Case Results[/]", style="cyan"))
    console.print()

    tbl = Table(
        box=box.ROUNDED,
        show_header=True,
        header_style="bold cyan",
        border_style="dim",
        expand=True,
    )
    tbl.add_column("ID",          style="bold", width=8)
    tbl.add_column("Description", max_width=36)
    tbl.add_column("Format",      justify="center", width=8)
    tbl.add_column("No Halluc.",  justify="center", width=10)
    tbl.add_column("Sem. Equiv.", justify="center", width=10)
    tbl.add_column("Confidence",  justify="center", width=10)
    tbl.add_column("BN Cover.",   justify="center", width=10)
    tbl.add_column("Composite",   justify="center", width=10)
    tbl.add_column("Status",      justify="center", width=8)

    for r in sorted(report.results, key=lambda x: x.test_case.id):
        s = r.scores
        if not r.llm_call_succeeded:
            tbl.add_row(
                r.test_case.id,
                r.test_case.description[:36],
                "—", "—", "—", "—", "—", "—",
                "[bold red]ERROR[/]",
            )
        else:
            tbl.add_row(
                r.test_case.id,
                r.test_case.description[:36],
                _fmt(s.format_score),
                _fmt(s.hallucination_score),
                _fmt(s.semantic_equivalence_score),
                _fmt(s.confidence_score),
                _fmt(s.bottleneck_coverage_score),
                _fmt(s.composite_score),
                _pass_fail(s.composite_score, PASS_THRESHOLD),
            )

    console.print(tbl)

    # ── Aggregate summary table ───────────────────────────────────────────
    console.print()
    console.print(Rule("[bold]Aggregate Summary[/]", style="cyan"))
    console.print()

    summary_tbl = Table(box=box.SIMPLE, show_header=False, padding=(0, 2))
    summary_tbl.add_column("Metric", style="bold")
    summary_tbl.add_column("Score")
    summary_tbl.add_column("Weight", style="dim")

    from src.eval.metrics import SCORE_WEIGHTS

    summary_tbl.add_row(
        "Format Adherence",
        _fmt(report.avg_format_score),
        f"{SCORE_WEIGHTS['format_score']:.0%}",
    )
    summary_tbl.add_row(
        "Hallucination Resistance",
        _fmt(report.avg_hallucination_score),
        f"{SCORE_WEIGHTS['hallucination_score']:.0%}",
    )
    summary_tbl.add_row(
        "Semantic Equivalence",
        _fmt(report.avg_semantic_equivalence_score),
        f"{SCORE_WEIGHTS['semantic_equivalence_score']:.0%}",
    )
    summary_tbl.add_row(
        "LLM Confidence",
        _fmt(report.avg_confidence_score),
        f"{SCORE_WEIGHTS['confidence_score']:.0%}",
    )
    summary_tbl.add_row(
        "Bottleneck Coverage",
        _fmt(report.avg_bottleneck_coverage_score),
        f"{SCORE_WEIGHTS['bottleneck_coverage_score']:.0%}",
    )
    summary_tbl.add_row("", "", "")
    summary_tbl.add_row(
        "[bold]Composite Score[/]",
        f"[{_score_color(report.avg_composite_score)}][bold]{report.avg_composite_score:.1%}[/][/]",
        "—",
    )

    console.print(summary_tbl)

    # ── Pass/fail summary ─────────────────────────────────────────────────
    console.print()
    overall_color = "green" if report.failed_cases == 0 and report.error_cases == 0 else "red"
    console.print(
        Panel(
            f"[bold {overall_color}]{'✅ ALL PASSED' if report.failed_cases == 0 and report.error_cases == 0 else '❌ SOME FAILURES'}[/]\n\n"
            f"  Total Cases : [bold]{report.total_cases}[/]\n"
            f"  Passed      : [bold green]{report.passed_cases}[/]\n"
            f"  Failed      : [bold red]{report.failed_cases}[/]\n"
            f"  Errors      : [bold yellow]{report.error_cases}[/]",
            title=f"Prompt Version: {report.prompt_version}",
            border_style=overall_color,
        )
    )

    # ── Worst case diagnostics ────────────────────────────────────────────
    if report.worst_cases:
        console.print()
        console.print(Rule("[bold]Worst Cases — Diagnostics[/]", style="dim red"))
        for r in report.worst_cases:
            if r.scores.composite_score < PASS_THRESHOLD:
                console.print(
                    f"\n  [bold red]{r.test_case.id}[/] — {r.test_case.description}"
                )
                console.print(f"    Composite   : {_fmt(r.scores.composite_score)}")
                if r.hallucinated_change_count:
                    console.print(
                        f"    Hallucinations: [bold red]{r.hallucinated_change_count}[/] "
                        f"out of {r.claimed_change_count} claimed change(s)"
                    )
                if not r.semantic_equivalent:
                    console.print(
                        f"    Screener    : [bold red]NOT semantically equivalent[/] "
                        f"(confidence={r.semantic_confidence:.0%})"
                    )
                if r.error_message:
                    console.print(f"    Error       : [bold red]{r.error_message}[/]")

    # ── JSON output (optional) ────────────────────────────────────────────
    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        report_dict = {
            "meta": {
                "prompt_version": report.prompt_version,
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "dataset": str(dataset_path),
                "pass_threshold": PASS_THRESHOLD,
            },
            "summary": {
                "total_cases": report.total_cases,
                "passed_cases": report.passed_cases,
                "failed_cases": report.failed_cases,
                "error_cases": report.error_cases,
                "avg_format_score": report.avg_format_score,
                "avg_hallucination_score": report.avg_hallucination_score,
                "avg_semantic_equivalence_score": report.avg_semantic_equivalence_score,
                "avg_confidence_score": report.avg_confidence_score,
                "avg_bottleneck_coverage_score": report.avg_bottleneck_coverage_score,
                "avg_composite_score": report.avg_composite_score,
            },
            "results": [
                {
                    "id": r.test_case.id,
                    "description": r.test_case.description,
                    "tags": r.test_case.tags,
                    "llm_call_succeeded": r.llm_call_succeeded,
                    "error_message": r.error_message,
                    "original_sql": r.test_case.original_sql,
                    "optimized_sql": r.optimized_sql,
                    "claimed_change_count": r.claimed_change_count,
                    "hallucinated_change_count": r.hallucinated_change_count,
                    "verified_changes": r.verified_changes,
                    "semantic_equivalent": r.semantic_equivalent,
                    "semantic_confidence": r.semantic_confidence,
                    "scores": {
                        "format_score": r.scores.format_score,
                        "hallucination_score": r.scores.hallucination_score,
                        "semantic_equivalence_score": r.scores.semantic_equivalence_score,
                        "confidence_score": r.scores.confidence_score,
                        "bottleneck_coverage_score": r.scores.bottleneck_coverage_score,
                        "composite_score": r.scores.composite_score,
                    },
                }
                for r in report.results
            ],
        }

        with output_path.open("w", encoding="utf-8") as fh:
            json.dump(report_dict, fh, indent=2)

        console.print(f"\n  💾 Results saved to [bold cyan]{output_path}[/]")

    console.print()
    return 0 if (report.failed_cases == 0 and report.error_cases == 0) else 1


# ── CLI argument parsing ──────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Offline prompt evaluation suite for the SQL optimization system prompts.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python scripts/evaluate_prompts.py
  python scripts/evaluate_prompts.py --max-cases 3
  python scripts/evaluate_prompts.py --tags correlated_subquery
  python scripts/evaluate_prompts.py --output eval/results/run.json
        """,
    )
    parser.add_argument(
        "--dataset",
        default="eval/golden_dataset.jsonl",
        help="Path to the JSONL golden dataset (default: eval/golden_dataset.jsonl)",
    )
    parser.add_argument(
        "--max-cases",
        type=int,
        default=None,
        metavar="N",
        help="Limit to the first N test cases (useful for quick checks)",
    )
    parser.add_argument(
        "--tags",
        nargs="+",
        default=None,
        metavar="TAG",
        help="Only run cases that have at least one of these tags",
    )
    parser.add_argument(
        "--output",
        default=None,
        metavar="FILE",
        help="Save full results as JSON to this file (e.g., eval/results/run_001.json)",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    sys.exit(run_evaluation(args))
